global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using Vanguard.Common;
global using Vanguard.ViewModels;
global using Vanguard.Views;
global using WinUICommunity;
global using static Vanguard.Common.AppHelper;
