// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace Vanguard.Desktop;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"Vanguard.Desktop.Views.HomeLandingPage", typeof(Vanguard.Desktop.Views.HomeLandingPage)},
        {"Vanguard.Desktop.Views.Reports.Report1Page", typeof(Vanguard.Desktop.Views.Reports.Report1Page)},
        {"Vanguard.Desktop.Views.Reports.Report2Page", typeof(Vanguard.Desktop.Views.Reports.Report2Page)},
        {"Vanguard.Desktop.Views.Reports.Report3Page", typeof(Vanguard.Desktop.Views.Reports.Report3Page)},
        {"Vanguard.Desktop.Views.AllContractsPage", typeof(Vanguard.Desktop.Views.AllContractsPage)},
        {"Vanguard.Desktop.Views.MyContractsPage", typeof(Vanguard.Desktop.Views.MyContractsPage)},
        {"Vanguard.Desktop.Views.MyCrewCallsPage", typeof(Vanguard.Desktop.Views.MyCrewCallsPage)},
    };
}
