global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using DevWinUI;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using Vanguard.Desktop.Common;
global using Vanguard.Desktop.ViewModels;
global using Vanguard.Desktop.Views;
global using static Vanguard.Desktop.Common.AppHelper;
